from abc import ABC, abstractmethod
from typing import List
import numpy as np

from quad_sim.bases.rigidbody import RigidBody
from quad_sim.bases.motor import MotorBase
from quad_sim.references.bodyFixed import BodyFixed
from quad_sim.bases.environment import EnvironmentBase
from quad_sim.bases.state import StateVector

from quad_sim.funcs import compute_aB,compute_alphaB,compute_q_rate


class DynamicsBase(ABC):
    def __init__(self, body: RigidBody, motors: List[MotorBase]):
        if not isinstance(body, RigidBody):
            raise TypeError(f"body must be an instance of RigidBody, got {type(body)}")
        if not isinstance(motors, list) or not all(isinstance(motor, MotorBase) for motor in motors):
            raise TypeError("motors must be a list of MotorBase instances")
        
        self.body = body
        self.motors = motors
    
    @property
    def mass(self) -> float:
        """
        The mass of the drone in kilograms.

        :return: The mass of the drone.
        :rtype: float
        """
        return self.body.mass
    
    @property
    def inertia_tensor(self) -> np.ndarray:
        """
        The inertia tensor of the drone, represented as a 3x3 numpy array.

        :return: The inertia tensor of the drone.
        :rtype: np.ndarray
        """
        return self.body.inertia_tensor
    
    @property
    @abstractmethod
    def rotor_rates(self) -> dict[str, float]:
        """
        Must return a dictionary of values for each motor, this is going to be used in the motor model to calculate the forces and moments generated by each motor.

        :return: A dictionary of RPM values for each rotor.
        :rtype: dict[str, float]
        """
        pass

    def _compute_internal_forces(self) -> tuple[BodyFixed, BodyFixed]:
        """
        Must calculate the internal forces and moments acting on the drone caused by the motors and other internal components.
        This method should return a tuple containing the total thrust and moments generated by the drone's motors in the body-fixed frame.

        :return: A tuple containing the internal thrust and moments acting on the drone.
        :rtype: tuple[BodyFixed, BodyFixed]
        """

        thrust, moments = BodyFixed(0, 0, 0), BodyFixed(0, 0, 0)
        for motor in self.motors:
            motor_thrust, motor_moment = motor.compute_forces()
            thrust += motor_thrust
            moments += motor_moment
            moments += motor.position*motor_thrust  # Add the moment generated by the thrust at the motor's position
        return thrust, moments
    
    def compute_forces_and_moments(self, environment:EnvironmentBase, state:StateVector) -> tuple[BodyFixed, BodyFixed]:
        thrust, moments = BodyFixed(0, 0, 0), BodyFixed(0, 0, 0)
        intThrust, intMoment = self._compute_internal_forces()
        extThrust, extMoment = environment.apply_effects(state)

        thrust += intThrust + extThrust
        moments += intMoment + extMoment

        return thrust, moments
    
    def compute_accelerations(self, F:BodyFixed, M:BodyFixed, state:StateVector) -> tuple[BodyFixed, BodyFixed]:
        """
        Compute the linear and angular accelerations of the drone based on the applied forces and moments.

        :param F: The total force acting on the drone in the body-fixed frame.
        :type F: BodyFixed
        :param M: The total moment acting on the drone in the body-fixed frame.
        :type M: BodyFixed
        
        :return: A tuple containing the linear acceleration and angular acceleration of the drone.
        :rtype: tuple[BodyFixed, BodyFixed]
        """
        a = compute_aB(self.mass,F,state.omega,state.velocity)  # Linear acceleration using Newton's second law
        alpha = compute_alphaB(self.inertia_tensor,M,state.omega)  # Angular acceleration using Euler's rotation equations
        q_rate = compute_q_rate(state.quaternion, state.omega)  # Quaternion rate of change based on current angular velocity
        return a, alpha, q_rate

    def set_motor_rpm(self, rpms: list[float]) -> None:
        """
        Set the RPM squared values for each motor in the drone. 
        This method takes a list of RPM values corresponding to each motor and updates the internal state of the motors accordingly.
        """
        for motor, rpm in zip(self.motors, rpms):
            motor.set_rpm(rpm)
        pass
    
    
    
